travis:
  secure:
    BINSTAR_TOKEN: RgBtrAQ6Ye2lkxqvtGOmNletx6wrKTEZUGvymmFQYXIcktEpwlG/ztPDllqyug5wQtDkIjD0VgGeRtSi0XwBXKZjmalsssy7cu7JgPkjOPn1Vc949FE2PiM8j1eZYP4V4VnSyE42rM2dBOE+K3KnjCiNXJXcgisiQZPL4WisUYB/3hiKfuVgWnRsonnC2BwS+lmSBu57mQGCNrxMObD+0IIcdQpLRJoLRB8jqdOv+0nkrUtOo/5slY/kpy4Z2XT0k0WSXFMecuLIYLFl8DnhiR8Cb/H14nllywYlMmVnEE5MJp9zo0/qUHsWszGjg8bSSRpB4+chNqZOjZUi9ZftfWa4hrVfqLP40pnFtJ1b1Og2VIscwfDBSOBtJi68OOjLS5B7hjygJmRC+DIvF1Hgax6UCrHgOPbWGZbgNxcyWLsXO5lsy0RuhGgSa2Poz/vwbspGVmZylspwKCsHSBuOwK9PTHfvZHRMkRSRoSs038K+kgrlBgBlVEeWvFDk8KeqBI0PLDCCYgBikL5vTIHbBO6d27dvYyYluWDRqjPXtBVzQDvaqFYPpOV8SWbefHh02wIUGq0IJ69XCtgFQ75tq9LR4MUB69RNUNkiT/itrR+krTWTv038nocZ+08u7pK6/euqvKSDP7IPJ6FndiGR7GH+xA1iVLno6MJgNIK6uUI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
